In [2]:
import torch
print(torch.__version__)

2.9.1+cpu


## Tensors

In [3]:
## using empty
torch.empty(4,4)

tensor([[-2.6677e-23,  1.0019e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

It allocates memory to tensors and shows values present at that memory.

In [4]:
# using zero
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

It create tensor with all values as 0.

In [5]:
# using ones 
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

It create tensors with all values 1.

In [6]:
torch.rand(2,3)

tensor([[0.7732, 0.0790, 0.2587],
        [0.4343, 0.6246, 0.0256]])

It create tensors with all random values between 0 to 1. Limitation is after every run of the same code will produce different tensors value.

In [7]:
## To overcome above limitation
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
## using tensor
torch.tensor([[5,10,15],[20,25,30]])

tensor([[ 5, 10, 15],
        [20, 25, 30]])

It is used to generate customize or user defined tensors where user has to pass all values to be stored in tensors.

## Tensor shape

In [9]:
t1 = torch.tensor([[1,2],[3,4],[4,5],[6,7]])

In [10]:
t1.shape

torch.Size([4, 2])

## Tensor data type

In [11]:
t1.dtype

torch.int64

In [12]:
## declare data type of tensor at the time of executation
t3 = torch.tensor([[1,2],[3,5]],dtype=torch.float32)

# Mathematical operations

In [13]:
## Scalar addition
print(t1 + 10)

tensor([[11, 12],
        [13, 14],
        [14, 15],
        [16, 17]])


All operations are same except operators.

In [14]:
print(t1-1)
print(t1*4)
print(t1**2)
print(t1/2)

tensor([[0, 1],
        [2, 3],
        [3, 4],
        [5, 6]])
tensor([[ 4,  8],
        [12, 16],
        [16, 20],
        [24, 28]])
tensor([[ 1,  4],
        [ 9, 16],
        [16, 25],
        [36, 49]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000],
        [2.0000, 2.5000],
        [3.0000, 3.5000]])


In [15]:
## Elements wise operations

In [16]:
t2 = torch.tensor([[1,2],
                   [2,3],
                   [3,4],
                   [4,5]])

In [17]:
t1+t2

tensor([[ 2,  4],
        [ 5,  7],
        [ 7,  9],
        [10, 12]])

In [18]:
t1-t2
t1*t2
t1/t2

tensor([[1.0000, 1.0000],
        [1.5000, 1.3333],
        [1.3333, 1.2500],
        [1.5000, 1.4000]])

In [19]:
## Reduction operation

Reduction operation are used to reduce the tensor to a scalar value.

In [20]:
print(torch.sum(t2))

tensor(24)


In [21]:
print(torch.mean(t3))

tensor(2.7500)


In [22]:
print(torch.median(t3))

tensor(2.)


In [23]:
print(torch.std(t3))

tensor(1.7078)
